services:
  redis:
    image: redis:7-alpine
    container_name: nckh-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    container_name: nckh-backend
    build:
      context: ./back_end
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379/0
    depends_on:
      - redis
    ports:
      - "5000:5000"

  frontend:
    container_name: nckh-frontend
    build:
      context: ./front_end/web_frontend
    ports:
      - "3001:80"
    environment:
      - BACKEND_URL=http://backend:5000
    depends_on:
      - backend

volumes:
  redis_data:
